// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA91HmyhmZVBzm4UaK5oHs_V5ru1cADmmI',
    appId: '1:858360232413:web:d5f4e86bc04083a53d1e34',
    messagingSenderId: '858360232413',
    projectId: 'mynotesbeginer',
    authDomain: 'mynotesbeginer.firebaseapp.com',
    storageBucket: 'mynotesbeginer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqUputo6_lkrj_DF0-Uc2jOWIAG3BfLkA',
    appId: '1:858360232413:android:ddb6210f16eeb7c93d1e34',
    messagingSenderId: '858360232413',
    projectId: 'mynotesbeginer',
    storageBucket: 'mynotesbeginer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADNAjYFkdgWmEYqGtuteW1bp6cm6li4uo',
    appId: '1:858360232413:ios:451eda2f5b7159593d1e34',
    messagingSenderId: '858360232413',
    projectId: 'mynotesbeginer',
    storageBucket: 'mynotesbeginer.appspot.com',
    iosClientId: '858360232413-k89sadv1b3uf78gkan5ojgr8uqlqb30d.apps.googleusercontent.com',
    iosBundleId: 'com.phamnhantucode.mynotesbeginer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADNAjYFkdgWmEYqGtuteW1bp6cm6li4uo',
    appId: '1:858360232413:ios:fde1c63cfecc99213d1e34',
    messagingSenderId: '858360232413',
    projectId: 'mynotesbeginer',
    storageBucket: 'mynotesbeginer.appspot.com',
    iosClientId: '858360232413-6guhvl66j2o4ukr261bfrb17qtka0ae6.apps.googleusercontent.com',
    iosBundleId: 'com.phamnhantucode.mynotesbeginer.RunnerTests',
  );
}
